spring.application.name=springaitool
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=arnav
spring.datasource.password=12345

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.webclient.connect-timeout=60000
spring.webclient.read-timeout=60000

spring.ai.retry.max-attempts=3
spring.ai.retry.backoff.initial-interval=2000
spring.ai.retry.backoff.multiplier=2
spring.ai.retry.backoff.max-interval=10000

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
